import { NextRequest, NextResponse } from 'next/server'
import { stat, readFile, unlink } from 'fs/promises'
import path from 'path'

export const runtime = 'nodejs'

/**
 * GET  /api/admissions/upload/[id]         → serve a stored document inline (View)
 * GET  /api/admissions/upload/[id]?download=1 → force download (Download)
 * DELETE /api/admissions/upload/[id]       → remove a stored document
 *
 * The id is an opaque opaque token generated by the upload route. Only the
 * exact file it points to is ever served — no path traversal (ids containing
 * path separators are rejected outright).
 */

const UPLOAD_DIR = path.join(process.cwd(), 'db', 'uploads', 'admissions')

const MIME_BY_EXT: Record<string, string> = {
  pdf: 'application/pdf',
  jpg: 'image/jpeg',
  png: 'image/png',
}

function isValidId(id: string): boolean {
  return /^[a-z0-9-]+\.(pdf|jpg|png)$/i.test(id)
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  if (!isValidId(id)) {
    return NextResponse.json({ success: false, error: 'Invalid document id.' }, { status: 400 })
  }

  const filePath = path.join(UPLOAD_DIR, id)
  try {
    const info = await stat(filePath)
    if (!info.isFile()) throw new Error('not a file')
    const data = await readFile(filePath)
    const ext = id.split('.').pop()!.toLowerCase()
    const download = req.nextUrl.searchParams.get('download') === '1'

    return new NextResponse(new Uint8Array(data), {
      headers: {
        'Content-Type': MIME_BY_EXT[ext] || 'application/octet-stream',
        'Content-Length': String(info.size),
        'Content-Disposition': `${download ? 'attachment' : 'inline'}; filename="${id}"`,
        'Cache-Control': 'private, max-age=3600',
      },
    })
  } catch {
    return NextResponse.json(
      { success: false, error: 'Document not found. It may have been removed.' },
      { status: 404 }
    )
  }
}

export async function DELETE(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  if (!isValidId(id)) {
    return NextResponse.json({ success: false, error: 'Invalid document id.' }, { status: 400 })
  }
  try {
    await unlink(path.join(UPLOAD_DIR, id))
    return NextResponse.json({ success: true })
  } catch {
    // Deleting a missing file is fine — the record is being cleared anyway.
    return NextResponse.json({ success: true })
  }
}
