/**
 * Schedule PDF — landscape printable examination timetable grid.
 *
 * Spec: shift times shown ONCE in the header. Cells show only subject +
 * compact shift indicator (1st/2nd). No repeated time in every cell.
 * No room, no invigilator.
 */

import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { ExamDTO } from '@/lib/exams/types'
import type { ConsolidatedTimetable } from '@/lib/exams/schedule/consolidate'
import { formatDateLong } from '@/lib/exams/format-helpers'

export function generateSchedulePDF(exam: ExamDTO, timetable?: ConsolidatedTimetable): void {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()

  // Header — centered
  doc.setFontSize(14); doc.setFont('helvetica', 'bold')
  doc.text('Demo School of Scholario', pageW / 2, 14, { align: 'center' })
  doc.setFontSize(11)
  doc.text(exam.name, pageW / 2, 20, { align: 'center' })
  doc.setFontSize(9); doc.setFont('helvetica', 'normal')
  const dateRange = exam.startDate && exam.endDate
    ? `${formatDateLong(exam.startDate)} – ${formatDateLong(exam.endDate)}`
    : ''
  doc.text(`Academic Session ${exam.session ?? ''}  ·  ${dateRange}`, pageW / 2, 25, { align: 'center' })

  // Shift timings — shown ONCE
  let shiftHeader = ''
  if (timetable && timetable.rows.length > 0) {
    const byDate = new Map<string, typeof timetable.rows>()
    for (const row of timetable.rows) {
      if (!byDate.has(row.date)) byDate.set(row.date, [])
      byDate.get(row.date)!.push(row)
    }
    const firstDate = Array.from(byDate.keys()).sort()[0]
    const firstDateRows = byDate.get(firstDate)!
    if (firstDateRows.length > 1) {
      shiftHeader = firstDateRows.map((r, i) => `${i === 0 ? '1st' : '2nd'} Shift: ${r.startTime}–${r.endTime}`).join('    ')
    } else {
      shiftHeader = `Exam Time: ${firstDateRows[0].startTime}–${firstDateRows[0].endTime}`
    }
  }
  if (shiftHeader) {
    doc.setFontSize(9)
    doc.text(shiftHeader, pageW / 2, 30, { align: 'center' })
  }
  doc.setFontSize(8); doc.setFont('helvetica', 'bold')
  doc.text('EXAMINATION TIMETABLE', pageW / 2, shiftHeader ? 35 : 30, { align: 'center' })

  // Build table: date × shift rows. Columns: Day/Date | [Shift] | class1 | class2 | ...
  const columns = timetable?.columns ?? []
  const hasShifts = timetable && timetable.rows.length > 0
    ? new Set(timetable.rows.map((r) => r.date)).size < timetable.rows.length
    : false

  const head = hasShifts
    ? [['Day / Date', 'Shift', ...columns.map((c) => c.label)]]
    : [['Day / Date', ...columns.map((c) => c.label)]]

  const body: string[][] = []
  if (timetable) {
    const byDate = new Map<string, typeof timetable.rows>()
    for (const row of timetable.rows) {
      if (!byDate.has(row.date)) byDate.set(row.date, [])
      byDate.get(row.date)!.push(row)
    }
    for (const [date, rows] of byDate) {
      const dateLabel = formatDateLong(date)
      const dayLabel = rows[0]?.dayLabel ?? ''
      for (const row of rows) {
        const cells = columns.map((_, colIdx) => {
          const cell = row.cells[colIdx]
          return cell ? cell.label : '—'
        })
        if (hasShifts) {
          body.push([`${dayLabel}\n${dateLabel}`, row.slotIndex === 0 ? '1st' : '2nd', ...cells])
        } else {
          body.push([`${dayLabel}\n${dateLabel}`, ...cells])
        }
      }
    }
  }

  autoTable(doc, {
    head,
    body,
    startY: shiftHeader ? 38 : 33,
    styles: { fontSize: 7, cellPadding: 1.5, valign: 'middle', overflow: 'linebreak' },
    headStyles: { fillColor: [15, 118, 110], textColor: 255, fontSize: 7 },
    columnStyles: hasShifts
      ? { 0: { fontStyle: 'bold', cellWidth: 22 }, 1: { cellWidth: 10, halign: 'center' } }
      : { 0: { fontStyle: 'bold', cellWidth: 25 } },
    alternateRowStyles: { fillColor: [245, 250, 249] },
  })

  const pageH = doc.internal.pageSize.getHeight()
  doc.setFontSize(7); doc.setFont('helvetica', 'normal')
  doc.text('Official examination timetable — generated by Scholario-OS', pageW / 2, pageH - 5, { align: 'center' })

  doc.save(`${exam.name.replace(/\s+/g, '-')}-schedule.pdf`)
}
