import { NextRequest, NextResponse } from 'next/server'
import { stat, readFile, unlink } from 'fs/promises'
import path from 'path'

export const runtime = 'nodejs'

/**
 * GET  /api/teachers/upload/[fileId]         → serve a stored photo/signature inline
 * GET  /api/teachers/upload/[fileId]?download=1 → force download
 * DELETE /api/teachers/upload/[fileId]       → remove a stored media file
 *
 * The fileId is an opaque token generated by the upload route. Only the
 * exact file it points to is ever served — no path traversal (ids
 * containing path separators are rejected outright).
 */

const UPLOAD_DIR = path.join(process.cwd(), 'db', 'uploads', 'teachers')

const MIME_BY_EXT: Record<string, string> = {
  jpg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
}

function isValidId(id: string): boolean {
  return /^[a-z0-9-]+\.(jpg|png|webp)$/i.test(id)
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ fileId: string }> }
) {
  const { fileId } = await params
  if (!isValidId(fileId)) {
    return NextResponse.json({ success: false, error: 'Invalid file id.' }, { status: 400 })
  }

  const filePath = path.join(UPLOAD_DIR, fileId)
  try {
    const info = await stat(filePath)
    if (!info.isFile()) throw new Error('not a file')
    const data = await readFile(filePath)
    const ext = fileId.split('.').pop()!.toLowerCase()
    const download = req.nextUrl.searchParams.get('download') === '1'

    return new NextResponse(new Uint8Array(data), {
      headers: {
        'Content-Type': MIME_BY_EXT[ext] || 'application/octet-stream',
        'Content-Length': String(info.size),
        'Content-Disposition': `${download ? 'attachment' : 'inline'}; filename="${fileId}"`,
        'Cache-Control': 'private, max-age=3600',
      },
    })
  } catch {
    return NextResponse.json(
      { success: false, error: 'File not found. It may have been removed.' },
      { status: 404 }
    )
  }
}

export async function DELETE(
  _req: NextRequest,
  { params }: { params: Promise<{ fileId: string }> }
) {
  const { fileId } = await params
  if (!isValidId(fileId)) {
    return NextResponse.json({ success: false, error: 'Invalid file id.' }, { status: 400 })
  }
  try {
    await unlink(path.join(UPLOAD_DIR, fileId))
    return NextResponse.json({ success: true })
  } catch {
    // Deleting a missing file is fine — the record is being cleared anyway.
    return NextResponse.json({ success: true })
  }
}
