import type { AdmissionApplication } from './types'
import { defaultInitialFormData, defaultInitialFeeData, defaultSectionReviews } from './defaults'

export const initialApplications: AdmissionApplication[] = [
  {
    id: 'APP-2026-001',
    admissionNo: 'ADM-2026-0841',
    studentId: 'STU-2026-0841',
    rollNo: '01',
    regNo: 'REG-CBSE-2026-9012',
    applicantName: 'Ira Malhotra',
    className: 'Class 2',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-27',
    lastUpdatedDate: '2026-07-28',
    status: 'Submitted',
    formData: defaultInitialFormData,
    feeData: defaultInitialFeeData,
    sectionReviews: defaultSectionReviews(),
    auditTrail: [
      { id: 'a1', timestamp: '2026-07-27 10:15 AM', action: 'Application Created', actor: 'Parent (Rajiv Malhotra)', notes: 'Wizard form initialized' },
      { id: 'a2', timestamp: '2026-07-27 10:30 AM', action: 'Submitted', actor: 'Parent (Rajiv Malhotra)', notes: 'Application submitted for admission verification' },
    ],
  },
  {
    id: 'APP-2026-002',
    admissionNo: 'ADM-2026-0842',
    studentId: 'STU-2026-0842',
    rollNo: '02',
    regNo: 'REG-CBSE-2026-9013',
    applicantName: 'Rohan Deshmukh',
    className: 'Grade 9',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-26',
    lastUpdatedDate: '2026-07-27',
    status: 'Under Review',
    formData: {
      ...defaultInitialFormData,
      firstName: 'Rohan',
      lastName: 'Deshmukh',
      className: 'Grade 9',
      fatherName: 'Sanjay Deshmukh',
      motherName: 'Anjali Deshmukh',
      previousSchool: 'Delhi Public School, Vasant Kunj',
      previousYear: '2024–2025',
    },
    feeData: defaultInitialFeeData,
    sectionReviews: {
      ...defaultSectionReviews(),
      previousSchool: { status: 'Needs Review', remarks: 'Previous Class IX registration code pending CBSE portal cross-check.' },
    },
    auditTrail: [
      { id: 'a3', timestamp: '2026-07-26 11:20 AM', action: 'Application Submitted', actor: 'Applicant Parent', notes: 'Submitted via Online Admission Portal' },
      { id: 'a4', timestamp: '2026-07-27 09:10 AM', action: 'Under Review', actor: 'Admission Officer (Dr. Iyer)', notes: 'Flagged Previous School record for CBSE portal cross-check' },
    ],
  },
  {
    id: 'APP-2026-003',
    admissionNo: 'ADM-2026-0843',
    studentId: 'STU-2026-0843',
    rollNo: '03',
    regNo: 'REG-CBSE-2026-9014',
    applicantName: 'Kavya Pillai',
    className: 'Class 1',
    section: 'B',
    academicSession: '2025–2026',
    submittedDate: '2026-07-25',
    lastUpdatedDate: '2026-07-27',
    status: 'Need Correction',
    formData: {
      ...defaultInitialFormData,
      firstName: 'Kavya',
      lastName: 'Pillai',
      className: 'Class 1',
      section: 'B',
      fatherName: 'Ramesh Pillai',
      previousYear: '2024–2025',
    },
    feeData: defaultInitialFeeData,
    sectionReviews: {
      ...defaultSectionReviews(),
      documents: { status: 'Needs Review', remarks: 'Transfer Certificate copy is blurry. Please upload clear scan.' },
    },
    generalRemarks: 'Document scan blurry. Please re-upload Transfer Certificate.',
    auditTrail: [
      { id: 'a5', timestamp: '2026-07-25 02:15 PM', action: 'Application Submitted', actor: 'Parent', notes: 'Form submitted' },
      { id: 'a6', timestamp: '2026-07-27 10:00 AM', action: 'Returned for Correction', actor: 'Admission Desk', notes: 'Flagged documents section for re-upload' },
    ],
  },
  {
    id: 'APP-2026-004',
    admissionNo: 'ADM-2026-0844',
    studentId: 'STU-2026-0844',
    rollNo: '04',
    regNo: 'REG-CBSE-2026-9015',
    applicantName: 'Devansh Verma',
    className: 'Class 3',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-24',
    lastUpdatedDate: '2026-07-27',
    status: 'Approved',
    formData: {
      ...defaultInitialFormData,
      firstName: 'Devansh',
      lastName: 'Verma',
      className: 'Class 3',
      fatherName: 'Alok Verma',
      previousYear: '2024–2025',
    },
    feeData: defaultInitialFeeData,
    sectionReviews: defaultSectionReviews(),
    decisionBy: 'Principal Dr. Ananya Iyer',
    decisionDate: '2026-07-27',
    auditTrail: [
      { id: 'a7', timestamp: '2026-07-24 04:30 PM', action: 'Submitted', actor: 'Parent', notes: 'Form submitted' },
      { id: 'a8', timestamp: '2026-07-27 11:45 AM', action: 'Approved', actor: 'Principal Dr. Ananya Iyer', notes: 'All documents verified & principal interview cleared' },
    ],
  },
  {
    id: 'APP-2026-005',
    admissionNo: 'ADM-2026-0845',
    studentId: 'STU-2026-0845',
    rollNo: '05',
    regNo: 'REG-CBSE-2026-9016',
    applicantName: 'Siddharth Saxena',
    className: 'Grade 10',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-20',
    lastUpdatedDate: '2026-07-22',
    status: 'Rejected',
    formData: {
      ...defaultInitialFormData,
      firstName: 'Siddharth',
      lastName: 'Saxena',
      className: 'Grade 10',
      fatherName: 'Vipul Saxena',
      previousYear: '2024–2025',
    },
    feeData: defaultInitialFeeData,
    sectionReviews: {
      ...defaultSectionReviews(),
      classAllocation: { status: 'Incomplete', remarks: 'Grade 10 CBSE transfer seats quota exhausted for session.' },
    },
    decisionReason: 'Class 10 CBSE seat capacity limit reached for current session.',
    decisionBy: 'Admission Committee',
    decisionDate: '2026-07-22',
    rejectionRetentionDays: 60,
    rejectedAt: '2026-07-22',
    auditTrail: [
      { id: 'a9', timestamp: '2026-07-20 01:00 PM', action: 'Submitted', actor: 'Parent', notes: 'Submitted for Grade 10' },
      { id: 'a10', timestamp: '2026-07-22 03:20 PM', action: 'Rejected', actor: 'Admission Committee', notes: 'Seat limit reached for Grade 10' },
    ],
  },
  {
    id: 'APP-2026-006',
    admissionNo: 'ADM-2026-0840',
    studentId: 'STU-2026-0840',
    rollNo: '19',
    regNo: 'REG-CBSE-2026-9010',
    applicantName: 'Ananya Sharma',
    className: 'Class 2',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-15',
    lastUpdatedDate: '2026-07-18',
    status: 'Completed',
    formData: {
      ...defaultInitialFormData,
      firstName: 'Ananya',
      lastName: 'Sharma',
      className: 'Class 2',
      section: 'A',
      fatherName: 'Manish Sharma',
      previousYear: '2024–2025',
    },
    feeData: defaultInitialFeeData,
    sectionReviews: defaultSectionReviews(),
    decisionBy: 'Principal Dr. Ananya Iyer',
    decisionDate: '2026-07-18',
    auditTrail: [
      { id: 'a11', timestamp: '2026-07-15 10:00 AM', action: 'Submitted', actor: 'Parent', notes: 'Submitted' },
      { id: 'a12', timestamp: '2026-07-18 02:00 PM', action: 'Admission Completed & Enrolled', actor: 'Admission Desk', notes: 'Official credentials & letter issued' },
    ],
    generatedCredentials: {
      loginId: 'ANANYA_2026',
      tempPassword: 'Scholario@2026',
      portalUrl: 'https://portal.scholario.app',
    },
    notificationsSent: {
      sms: true,
      email: true,
      whatsapp: true,
      dispatchedAt: '2026-07-18 02:05 PM',
    },
  },
  {
    id: 'APP-2026-007',
    admissionNo: 'ADM-DRAFT-007',
    studentId: 'STU-DRAFT-007',
    rollNo: '—',
    regNo: '—',
    applicantName: 'Aarush Goel',
    className: 'Nursery',
    section: 'A',
    academicSession: '2025–2026',
    submittedDate: '2026-07-28',
    lastUpdatedDate: '2026-07-28',
    status: 'Draft',
    formData: {
      ...defaultInitialFormData,
      firstName: 'Aarush',
      lastName: 'Goel',
      className: 'Nursery',
      fatherName: 'Pankaj Goel',
      previousYear: '2024–2025',
    },
    feeData: defaultInitialFeeData,
    sectionReviews: defaultSectionReviews(),
    auditTrail: [
      { id: 'a13', timestamp: '2026-07-28 08:30 AM', action: 'Draft Created', actor: 'Applicant Parent', notes: 'Application saved as draft' },
    ],
  },
]

// Initial value for the active application selection.
export const INITIAL_SELECTED_APPLICATION_ID = 'APP-2026-001'
